[package]
name = "trisha-wgpu"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
trident-lang = { path = "../../trident", default-features = false }
triton-vm = "2"
twenty-first = "1"
bincode = "1"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = "24"
