[package]
name = "trisha"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trisha"
path = "main.rs"

[features]
triton = ["dep:trident-lang", "dep:trisha-rs", "trisha-honeycrisp/triton"]
gpu    = ["trisha-honeycrisp/gpu"]

[dependencies]
trident-lang = { path = "../../trident", optional = true }
trisha-rs = { path = "../rs", optional = true }
trisha-wgpu = { path = "../wgpu", optional = true }
trisha-honeycrisp = { path = "../honeycrisp" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
bincode = "1"
base64 = "0.22"
ureq = { version = "2", features = ["json"] }
