"""Preserve exact completed consumer containers and final matrix evidence."""
from pathlib import Path
import gzip,hashlib,json,shutil,subprocess
R=Path(__file__).resolve().parent.parent;M=R/'measurements';CI=R/'trisha-native-ci';OUT=CI/'audit/native-distribution-20261002/consumers';OUT.mkdir()
jobs={11210134597:110719141712,11211150705:110719141736,11211176216:110719141743,11210544976:110719141770,11210842931:110719141796}
for id,job in jobs.items():
 root=M/'native-runs/36969090113'/str(id);api=json.loads((root/'api.json').read_text());dst=OUT/api['name'].removeprefix('candidate-');dst.mkdir()
 for name in ['api.json','retention.json']:shutil.copy2(root/name,dst/name)
 shutil.copy2(root/'artifact.zip',dst/'original-artifact.zip')
 command=['gh','api',f'repos/cyberia-to/trisha/actions/jobs/{job}/logs'];r=subprocess.run(command,capture_output=True);assert r.returncode==0
 (dst/'job.log.gz').write_bytes(gzip.compress(r.stdout,mtime=0));(dst/'job-log.stderr').write_bytes(r.stderr);(dst/'job-log.json').write_text(json.dumps(dict(command=command,exit_code=r.returncode,bytes=len(r.stdout),sha256=hashlib.sha256(r.stdout).hexdigest(),retained_as='job.log.gz'),indent=2)+'\n')
shutil.copytree(M/'frozen-corpus-matrix',CI/'audit/native-distribution-20261002/corpus-matrix')
for name in ['inspect-frozen-matrix.py','retain-frozen-consumers.py']:shutil.copy2(M/name,CI/'audit/native-distribution-20261002'/name)
with (CI/'audit/native-distribution-20261002/README.md').open('a') as stream:stream.write('''\n### Frozen distribution acceptance complete\n\nThe five native consumer jobs in run 36969090113 at\n`b2289e18207021fc8c53c546fe5cdcdc19bbd9c5` all passed. The local Mac ARM\nconsumer passed with the same exact six binary/corpus selections, taking\n135.66343954199692 seconds and peaking at 131678208 bytes sampled process-group\nRSS. `local-corpus-consumer/` retains its complete original command/result\narchive. `consumers/` retains each remote authenticated Actions ZIP, original\nAPI/hash inventory and byte-preserved compressed job log.\n\n`python3 -B -W error measurements/inspect-frozen-matrix.py` authenticated every\nconsumer container, required the successful exact original run, then invoked\n`check-corpus-matrix.py` against all six original producer packages and all six\nactual consumer result directories. `corpus-matrix/receipt.json` records all\n36 required native pairs passed, with 1692 exact case checks (47 per pair).\nThe check binds each consumer's installed Joy/Trisha identities, every selected\nproducer corpus and its expected outcomes, and the installed accepted kit.\nThe selected source is still `e4bac7ff...`; none of these receipts describes\nthe separate current-production package.\n\nThe additional free macOS 14 consumer ran on actual macOS 14.8.9 ARM64 in\nrun 36969075321 at the same selector revision. It passed the six corpora\n(282 case checks) and installed kit in 94.94185200000001 seconds, with a\n137854976-byte sampled process-group peak, under 5 GiB / 1800-second limits.\n`macos14-arm-consumer/` preserves the authenticated original artifact;\n`frozen-mac-consumers-inspection.json` independently checks that receipt and\nthe local Mac receipt. This qualifies the exercised installed Joy/Trisha\nconsumer commands on that observed OS. Trident/LSP and full proof generation\nwere not exercised there.\n\nAll six frozen native producers, their applicable CPU and package gates, all\n133 baseline execution fixtures on each producer, one actual full198 proof\ngate on the frozen Mac binary, and all 36 portable corpus pairs have passed.\nThe five remote binary/corpus/original producer containers and the complete\nMac198 evidence have durable existing-draft assets. No publication, tag or\ndefault-branch release candidacy is implied. The current source archive\n`734df69d...` is being validated separately in PR23 with its own binaries and\nnew full198 gate.\n\nActual producer hosts remain macOS 26.4.1 ARM, macOS 15.7.9 Intel, Ubuntu\n22.04/glibc 2.35 ARM and x64, Windows 11 ARM and Windows Server 2022 x64.\n`docs/reference/release-platforms.md` calls the older desktop floors initial\ncandidates/proposed policies; Windows 11 x64 and macOS 14 Intel remain\nunqualified projections. The extra macOS14 ARM consumer does not expand its\nmeasured command scope into complete desktop-floor qualification.\n''')
print('retained',len(jobs),'original native consumer containers')
