[package]
name = "trisha-honeycrisp"
version = "0.3.0"
edition = "2021"

[lib]
path = "lib.rs"

[[bin]]
name = "bench-mine"
path = "bench_mine.rs"

[features]
triton = ["dep:trident-lang"]
gpu    = ["dep:aruminium"]

[dependencies]
trident-lang = { version = "0.4.0", path = "../../trident", optional = true, default-features = false }
triton-vm = "=7.0.0"
twenty-first = "1"
bincode = "1"
rayon = "1"

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
acpu = { version = "0.2.0", path = "../../honeycrisp/acpu" }
aruminium = { version = "0.2.0", path = "../../honeycrisp/aruminium", optional = true }
